### ISSUE TITLE
Feature: User can add footprint

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can visit a landing page and calculate page where they can interact with the form and click submit the form.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see the home page and read a little bit about Carbon Footprint and they will find a link at the bottom of the home page to access the quiz which calculate Carbon Footprint according to their daily activities. User can access both home page and calculation page at Nav Bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 12 02 45 PM](https://user-images.githubusercontent.com/36710918/201754744-e835f69e-ee65-4d53-b23b-0034913bb86b.png)
![Screen Shot 2022-11-14 at 12 03 24 PM](https://user-images.githubusercontent.com/36710918/201754800-32aeeec6-371c-497e-9c68-7addda2bced3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set up appropriate files and link `css` and `js` files as required.
- [x] Create a new `div` that contain Navigation Bar with Home/Calculate link and a drop down menu.
- [x] Make sure that click targets are `<a>` for swapping view between home and calculate.
- [x] Add required attribute in according to view swapping `[data-view=""]`
- [x] Create a new `div` with `[data-view="home-page"]` that will nest all the home page items.
- [x] Create a new `div` for Hero image and texts.
- [x] Create a new `div` that utilize `flex-box` feature to organize images and paragraphs.
- [x] Add horizontal line that span across the 100% width of flexbox.
- [x] Add `button` named CALCULATE and click listener that swap view to calculate page.
- [x] Add footer `div` and text `Powered by: Climatiq` and make the word `Climatiq` an `a` element to link user to external website upon click.
- [x] Create a new `div` with `[data-view="calculate-page"]` that will nest all the calculate page items.
- [x] Add header for the calculate page.
- [x] Create a new `div` that utilize `flex-box` feature to organize images and form elements.
- [x] Create a new `form` element.
- [x] Create 4 new `input` with `type="radio"` and set all the `name` attribute to `vehicle-picked`.
- [x] Create 4 new `input` with `type="range"` as number input.
- [x] Add event listener to input type range in order to update value in real time.
- [x] Create submit `button` for the form named FINISH.
- [x] Add event listener for the `form` element when submit button is clicked and store the data to a new object.
- [x] Include `preventDefault()` method for the submit event.
- [x] Clear all the form input with `.reset()` method
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
