### ISSUE TITLE
Feature: User can see daily result

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User is directed to a new page where they are able to see their footprint result in a table format and a bar graph with the date the calculation was taken.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user complete and submit the form, the data is sent with the HTTPRequest to Climatiq API and return an object with the results. The returned data is parsed and re-structure into a formatted DOM tree as well as plugged into graph which are then rendered onto the result page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 1 54 11 PM](https://user-images.githubusercontent.com/36710918/201776044-95921bb1-2e5d-48c6-b84c-6bac37d9d74f.png)
![Screen Shot 2022-11-14 at 1 55 09 PM](https://user-images.githubusercontent.com/36710918/201776182-b638c1c7-5778-4ddd-9384-6faf2d88c7a1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new `div` for result page with attribute `data-view="result"`.
- [x] Create a new `div` with flex-box design.
- [x] Add a new `.row`, one `column-full` and two `column-half`.
- [x] Inside `column-full` add a centered text for date.
- [x] First `column-half` will display result in `Number` format.
- [x] Add placeholder text "0" for all the results.
- [x] Add units in various sizes.
- [x] Send `column-half` will display result in graph format.
- [x] Each bar will represent each type of gases.
- [x] On calculate page, add `data-view="result"` to FINISH `<button>`.
- [x] Add event listener to FINISH `button` to with callback function `viewSwap` to switch to result page.
- [x] Add a new function `getFootprint` that takes form data object as argument.
- [x] Within the function `getFootprint` parse the argument object to match API format.
- [x] Within the function set up a new `XMLHttpRequest()`.
- [x] Set up the correct `.open()`, `.responseType` and `.addEventLisenter('load', function() {})`.
- [x] within event listener, parse the return JSON and extract the carbon mass results and store it into data model object.
- [x] Query select HTML elements that need to be updated with the result.
- [x] Update the HTML elements `textContent` according to the result.
- [x] Add `getFootprint` function inside `formHandle` function so it will fetch the data and update result page when the form is submit.
- [x] Modify `data` object model and add `entryId` to keep as unique identifier, add `editing: null;` property for future editing, and add footprint array property to keep store all the footprint entires.
- [x] Set up local storage to store `data` object model.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
