### ISSUE TITLE
Feature: User can see footprint history

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to access a page that contain footprint history. User can see a graph displaying footprint impact (kg) vs time (date) and a table with footprint information sorted by newest to oldest entry. User can click on individual footprint to access the result page containing the picked entry. User can now access the history page on Navigation Bar as well.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can access history page through NavBar or Menu dropdown. They will be able to see a line graph depicting the footprint date on X-axis, and footprint impact (kg) on Y-axis. Right below the line graph, user will also have access to history table where the each footprint entry will be display in numeric form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 2 03 20 PM](https://user-images.githubusercontent.com/36710918/201777546-a8b45d39-4a5c-4429-baf0-e69c6db18c12.png)
![Screen Shot 2022-11-14 at 2 03 46 PM](https://user-images.githubusercontent.com/36710918/201777598-04b86286-918e-4f7a-a05e-349fe3a606d3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new div for history page with attribute `data-view="history"`.
- [x] Add `a` element with attribute `data-view="history"` on Navbar for history page.
- [x] Query for this `a` element and add event listener for this `a` element that call on function `viewSwap` to switch view.
- [x] Add `a` element with attribute `data-view="history"` on Menu drop down for history page.
- [x] Query for this `a` element and add event listener for this `a` element that call on function `viewSwap` to switch view.
- [x] Create a new `div` that utilize flex-box feature to organize line graph and table.
- [x] Create a new `div` with `row` class and 2 new `div` with `column-full` class.
- [x] On the first `div.column-full` create a skeleton for line graph and query for the graph `table`.
- [x] Create a DOM tree for each `tr` to render onto line graph.
- [x] Loop through `data.footprints[index].total.[data]` and render DOM element with data onto the graph DOM.
- [x] On the second `div.column-full` create a skeleton for history table and query for the `table`
- [x] Within the skeleton, create `thead` with `date`, `CO2`, `CO2e`, `CH4`, `N2O` header
- [x] Create a DOM tree for each `tr` to render onto the table.
- [x] Loop through `data.footprints[index].total.[data]` and render DOM element with data onto the table DOM.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
