### ISSUE TITLE
Feature: User can edit previous footprint

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to edit footprint entry on history page and get have changed reflect on history line graph and history table.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
On history table, there are new edit button associate to each footprint. Once the user click on the edit, it will take user to calculate page but with new header telling user which date they are making the edit on. The calculate page will also be pre-populated with previous answer. Upon submitting the form again with new value, they will see the new result. This new result will also replace the old result in the table and line graph.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 2 09 21 PM](https://user-images.githubusercontent.com/36710918/201778530-6ad62da8-4ed1-4062-b0f5-812c1102bb3b.png)
![Screen Shot 2022-11-14 at 2 09 09 PM](https://user-images.githubusercontent.com/36710918/201778550-6e59bdd1-3535-4dec-98b4-46fa92b697d5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] On HTML file, add a new `th` in the `thead` of the history table for edit button/icon.
- [x] On the DOM tree render for history table `tr`, create another new `tr` element and add `button` onto `.textContent`.
- [x] Add an attribute with the unique id onto the `button` element.
- [x] Add this new `tr` element last in the order to match the correct column.
- [x] Add event listener on the Table and utilize event delegation to match tagName `BUTTON`.
- [x] Match the unique ID of the clicked `button` to data model object to get the matched object and store it onto `data.editing`.
- [x] Pre-populate the form with the matched object on calculate page.
- [x] Viewswap to the calculate page.
- [x] Within the check submit function, create a new condition to check if this footprint entry is new or editing.
- [x] If editing, after pulling new data from API, replace the existing data with new data.
- [x] Set `data.edting` to `null`
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
