### ISSUE TITLE
Feature: User can delete footprint

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete a footprint entry from the history table.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the history page, within the history table, on every footprint entry (row) there will be a delete button next to the edit button. User can click on the delete button, and when they do, a modal will pop and show the date of selected footprint. You can either confirm the deletion or click the "X" or any where outside the modal to cancel and the modal will disappear.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 2 10 47 PM](https://user-images.githubusercontent.com/36710918/201778709-438e2af3-e78a-4a81-879e-982f747557ee.png)
![Screen Shot 2022-11-14 at 2 10 35 PM](https://user-images.githubusercontent.com/36710918/201778713-ae437996-1f2d-4ceb-a209-1885260dd810.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] On HTML file, create a new `div` for the overlay with css property `position: absolute;` so that it doesn't affect the document flow.
- [x] Within the overlay, create a small modal window that has text contents and 2 `anchor` element for confirm and cancel.
- [x] On HTML file, add a new `th` in the `thead` of the history table for delete button/icon.
- [x] On the DOM tree render for history table `tr`, create another new `tr` element.
- [x] Add a unique attribute onto the button element.
- [x] Add this new `tr` element last in the order to match the correct column.
- [x] Add event listener on the Table and utilize event delegation to match target unique attribute.
- [x] Display overlay and delete modal when delete button is click
- [x] Match the unique ID of the clicked button to data model object to get the matched object.
- [x] Display `data.footprint[i].date` information of matched unique ID on the modal.
- [x] Add event listener for the confirm `button` that remove the selected object from data-model and update the line graph/history table when clicked.
- [x] Add event listener for the cancel "x" `button` that hide the delete modal when clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
